name: Pipeline CI

on:
  workflow_dispatch:

jobs:
  test:
    name: Test runner
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run application tests
        run: ./gradlew test